### ISSUE TITLE
Migrate Article

### ISSUE THREAD

**Issue by eag603** [isovera/icma#144]

**Comment by jardix22** [comment]
None of the articles are using the field_author. So, it was ignored on the migration file.
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/d116c189-b798-4e66-9ece-7bc841aa5892)

**Comment by jardix22** [comment]
As the article content type has some images, it was necessary to create a **File migration**.

**Comment by eag603** [comment]
Joseph will use module that will point to images on prod so we don't need to upgrade dev environment and Joseph will no longer be blocked.

**Comment by hatuhay** [comment]
@jardix22 
En el nodo /node/126990 no han llegado las imágenes de los banners.
Asumo que es igual con el resto de nodos que contienen imágenes de banner
