### ISSUE TITLE
Migrate Basic Page

### ISSUE THREAD

**Issue by eag603** [isovera/icma#145]

**Comment by hatuhay** [comment]
@jardix22
En el nodo /node/126990 no han llegado las imágenes de los banners.
Asumo que es igual con el resto de nodos que contienen imágenes de banner

**Comment by jardix22** [comment]
@hatuhay You can check them again.

**Comment by jardix22** [comment]
@hatuhay I registered a new ticket to work on the [WYSIWYG images migration](https://app.zenhub.com/workspaces/icma-d7---d9-migration-5fb82b0ae1a9c10015bb78bd/issues/isovera/icma/229).
