### ISSUE TITLE
Migrate Saved Search View

### ISSUE THREAD

**Issue by eag603** [isovera/icma#156]

**Comment by jardix22** [comment]
@eag603 @nickpizzo  There aren't any nodes registered. Should it be necessary to create a migration file?
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/b9a8b142-6250-4cbe-8ff9-a825940c14f1)

**Comment by amedina-icma** [comment]
I am unable to answers this question myself and have forwarded the issue onto to Bien and Fil.

**Comment by amedina-icma** [comment]
From Fil: "This view is not currently used. It exists as part of the original Job Center’s developer work and I believe was to have a feature on the site to save job searches."

This is a feature we do not plan to build.

**Comment by jardix22** [comment]
Thanks for your answer.
