### ISSUE TITLE
Migrate Search bar widget, Search or post widget, Three items row, Three items row-text, Tweet row widget

### ISSUE THREAD

**Issue by eag603** [isovera/icma#184]
- [x] Search bar widget
- [x] Three items row
- [x] Tweet row widget

**Not used**
- [ ] Three items row-text
- [ ] Search or post widget

**Comment by jardix22** [comment]
#### Paragraphs table equivalent migration
| D7      | D9 |
| ----------- | ----------- |
|Search bar widget|Dynamic View Widget|
|Three items row|Multiple items row|
|Tweet row widget|Dynamic View Widget|
