### ISSUE TITLE
Custom and Contributed Modules Planning

### ISSUE THREAD

**Issue by eag603** [isovera/icma#186]
Modules (contributed and custom)
Map current modules to D9 - 17 custom modules (not including Netforum, which is a separate ticket)

**Comment by eag603** [comment]
@nmangold  to take a quick look (1-2 hours) to confirm that all remaining modules are an easy transition to D9.

**Comment by nmangold** [comment]
The following are custom modules on the current D7 site. The bolded modules will likely need more time to convert to D8, and could likely benefit from structure improvments.

- crossposting
- *****header_image_block**
- *****helpers** (More investigation needed. This seems like a catch-all for many different module helpers.)
- icma_custom_menu
- icma_deployment
- icma_jobposts_newsletter
- *****icma_jobposts_social**
- icma_listing_page_settings
- **icma_redirect** (This might not be needed, and already done with redirect migrations.)
- icma_topic_interests
- migrate_icma
- *****netforum**
- netforum_sync_jobs
- related_content
- related_profiles
- *****url** (Can probably be implemented a different way. Link field?)
- views_header_advanced
- *****views_save**

**Comment by eag603** [comment]
Note from Nic: we can take the same approach as we're taking for the minimal approach on netforum and that is in scope.
