### ISSUE TITLE
Empty entities on Page module.

### ISSUE THREAD

**Issue by jardix22** [isovera/icma#230]
- Active Job Ads	
- Expired Job Ads	
- Featured Employers Widget	
- Grid Widget	
- Job Detail Widget (It has a single empty content).	
- Job Listings Widget	
- Map Widget	
- My Job Search Navigation Widget	
- Page module	
- Saved Jobs Dashboard Widget	
- Saved Jobs Widget	
- Saved Searches Dashboard Widget	
- Saved Searches Widget	
- Search Or Post Widget	
- Three Items Row - Text	
- Two Column Multimedia and Text (2/3 + 1/3)	
- Two Column Multimedia Widget

**Comment by jardix22** [comment]
All of them were ignored on D9, what should I do with them?

**Comment by amedina-icma** [comment]
I am unable to answers this question myself and have forwarded the issue onto to Bien and Fil.

**Comment by amedina-icma** [comment]
From Fil:

- Active Job Ads – Not used.
- Expired Job Ads – Not used.
- Featured Employers Widget – Not used.
- Grid Widget – Not used.
- Job Detail Widget – This is used. This is used to create the Job Details section on each of the job posts actual pages. There is a template for this widget that controls the output.
- Job Listings Widget – Not used.
- Map Widget – Not used.
- My Job Search Navigation Widget – Not used.
- Saved Jobs Dashboard Widget – Not used.
- Saved Jobs Widget – Not used.
- Page module – not used.
- Saved Searches Dashboard Widget – Not used.
- Saved Searches Widget – Not used.
- Search Or Post Widget – Not used.
- Three Items Row - Text – Not used.
- Two Column Multimedia Widget – Not used
- Two Column Multimedia and Text (2/3 + 1/3) – I don’t believe this is used either.
