### ISSUE TITLE
Uncertain Views

### ISSUE THREAD

**Issue by jardix22** [isovera/icma#236]
- [ ] All Answers: Broken view (https://icma.org/admin/structure/views/view/all_answers/edit)
- [ ] Answers to a Question: Broken view (https://icma.org/admin/structure/views/view/answers_to_a_question/edit )
- [ ] Broken links: Is it necessary? (https://icma.org/admin/structure/views/view/linkchecker_views_reports/edit)
- [ ] Discussions: Is it necessary? (https://icma.org/admin/structure/views/view/discussions/edit). It looks related to the group audience module.
- [ ] CMA blog: It is a duplicated view of **Blog Posts** (https://icma.org/admin/structure/views/view/icma_blog/edit).
- [ ] Questions List: Broken view.

**Comment by amedina-icma** [comment]
@jardix22 All the views listed can be removed.
