### ISSUE TITLE
Uncertain views - Part II

### ISSUE THREAD

**Issue by jardix22** [isovera/icma#242]
Empty views:
- Local Gov Life (/admin/structure/views/view/local_gov_life/edit)
- Saved Searches (/admin/structure/views/view/new_saved_searches/edit)

Old views:
- Search (/admin/structure/views/view/search/edit)
- Empty Legacy Content

**Comment by jardix22** [comment]
Andre, Could you check If I should migrate those views?

**Comment by amedina-icma** [comment]
@jardix22 You do not need to migrate the following views:

- Local Gov Life (/admin/structure/views/view/local_gov_life/edit)
- Saved Searches (/admin/structure/views/view/new_saved_searches/edit)
- Search (/admin/structure/views/view/search/edit)
- Empty Legacy Content
