### ISSUE TITLE
Should I remove first two fields of Subscription Form?

### ISSUE THREAD

**Issue by jardix22** [isovera/icma#249]
This block references a [Subscription Webform](https://icma.org/forms/subscribe-latest-icma).  Could you confirm for me if the form is used on another place? if not, Should I remove them?

![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/af76c4ae-11e1-464e-9da5-d387bf16ab5d)

**Comment by amedina-icma** [comment]
@jardix22 The webform on the live website does not use first and last name fields, only the email address field. You may remove the first and last name fields.
