### ISSUE TITLE
Netforum: Questions

### ISSUE THREAD

**Issue by jardix22** [isovera/icma#250]

**Comment by jardix22** [comment]
Andre, I need some test users with Groups/Roles assigned to validate the Roles Sync process, please.

**Comment by amedina-icma** [comment]
Hi @jardix22, please clarify for what environment and what information of the test users you will need. Do you need access to the Netforum AMS? Or are you referring solely to the Drupal CMS.

**Comment by jardix22** [comment]
My current SSO tests were done over the Netforum DEV environment. I have a registered user (jramos@isovera.com) on Netforum but It doesn't have any group assigned. So, I can't validate the ** Roles Sync ** process. 

Could you assign to my user some groups or/and share with me some users with assigned groups?

**Comment by amedina-icma** [comment]
@jardix22 Please see the following credentials:

Login to Test2 here:
https://dev.icma.org/
https://members.icma.org/nficmatest2/eweb/DynamicPage.aspx?WebCode=LoginRequired&expires=yes&Site=icmares&URL_success=https%3A%2F%2Fdev.icma.org%2Fuser%2Flogin%2Fnetforum%2F%7Btoken%7D%3Fdestination%3D

All passwords are set to 123.

Staff
Name: William Althaus
Login: zzwalthaus@icma.orgzz
Access level:
- All free website content
- Premium content, https://dev.icma.org/articles/member-news/applications-116
- PM subscriber content, https://dev.icma.org/articles/pm-magazine/2020-program-excellence-awards-community-health-and-safety

Member
Name: Tom Lundy
Login: zzjtomlundy@gmail.comzz
Access level:
- All free website content
- Premium content, https://dev.icma.org/articles/member-news/applications-116
- PM subscriber content, https://dev.icma.org/articles/pm-magazine/2020-program-excellence-awards-community-health-and-safety

PM subscriber (PM online subscription)
Name: account16 test
Login: zzzzmatt.watson87@gmail.comzzzz
Access level:
- All free website content
- PM subscriber content, https://dev.icma.org/articles/pm-magazine/2020-program-excellence-awards-community-health-and-safety

Free/NM
Name: account15 Test
Login: zzliveicma9@test.comzz
Access level:
- All free website content
