### ISSUE TITLE
Migrate inpage navigation to menu

### ISSUE THREAD

**Issue by eag603** [isovera/icma#251]

**Comment by jardix22** [comment]
@hatuhay Here you have an example of in-page navigation with 4th levels.
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/1f7e53f5-c708-4042-9864-354646b9c14f)

- http://dev-icma-org.pantheonsite.io/icma-executive-board
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/08104c8b-b444-4279-8a8a-e5be158d6efd)

Now, the in-page navigation block is rendering the 3rd level of the main menu.

**Comment by jardix22** [comment]
@hatuhay, you can work on this block while I'm migrating the rest of the in-page navigation menu links.
