### ISSUE TITLE
Migrate four columns members section paragraph

### ISSUE THREAD

**Issue by hatuhay** [isovera/icma#265]
http://dev-icma-org.pantheonsite.io/race-equity-and-social-justice

**Comment by jardix22** [comment]
It was created 2 views on
- **Blog posts**:  http://dev-icma-org.pantheonsite.io/admin/structure/views/view/blog_posts/edit/latest_block
- **News**: http://dev-icma-org.pantheonsite.io/admin/structure/views/view/articles/edit/latest_block

You could use twig tweak to insert them into the **four columns members section paragraph** paragraph.
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/7caf8912-114d-4384-96c1-248ac26661ae)

--- 
Also, I experimented with the Entity/Paragraph on D7 adding items on the **CONTENT COLUMN 1** field. So, it should be rendered like this: 
  ![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/333e8a40-3709-4605-a65b-cdd7c4f2be65)

**Comment by jardix22** [comment]
@hatuhay ^^
