### ISSUE TITLE
Add view as list, view as grid widget to serach views

### ISSUE THREAD

**Issue by hatuhay** [isovera/icma#274]
Exemple http://dev-icma-org.pantheonsite.io/topic-search/management
This choice should persist on the session and exposed as a class on each view page, ideally should be exposed on the body

**Comment by jardix22** [comment]
A new two-class were added on the `views-view--search.hmlt.twig`  template.
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/ee4f3c4f-4716-404c-8f11-ca97d6098c2c)
