### ISSUE TITLE
Migrate twitter views

### ISSUE THREAD

**Issue by hatuhay** [isovera/icma#278]

**Comment by hatuhay** [comment]
Views missing
Output is not what is on Drupal 7
D7 works with twitter module and that module has no D8 version.
The views output is different on D8

**Comment by jardix22** [comment]
**Job center**
http://dev-icma-org.pantheonsite.io/job-center
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/40c8d3a2-b6e1-4e44-a1f3-ca227de36bb3)

**Home page**
http://dev-icma-org.pantheonsite.io
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/66bf7751-0a1a-48cd-a42a-7252293244b1)

**Comment by jardix22** [comment]
@hatuhay ^^
