### ISSUE TITLE
Mark content as restricted, inject class to nodes when not accessible

### ISSUE THREAD

**Issue by hatuhay** [isovera/icma#284]

**Comment by jardix22** [comment]
**Premium content** 
URL: http://dev-icma-org.pantheonsite.io/node/14622/
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/42cfc1d1-2443-4fd6-ae6e-81d416571aa2)

**PM Content**
URL: http://dev-icma-org.pantheonsite.io/node/72684/
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/88c27974-ea19-46ac-a2e4-8baaef7d81b1)

**Search results** 
Now, all the premium/pm_content nodes have the `is-premium` class name.
URL: http://dev-icma-org.pantheonsite.io/topic-search/all?keyword=Managing+Border+Towns&date=All
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/23fabc7c-8f3c-4f21-81bd-9720411ba75d)

**Comment by jardix22** [comment]
@hatuhay ^^
