### ISSUE TITLE
Coronavirus Page

### ISSUE THREAD

**Issue by mnewberg1** [isovera/icma#295]
**Describe the bug**
http://dev-icma-org.pantheonsite.io/coronavirus-crisis-response
Compared to the D7 site, the D9 site has/ is
- ~~missing “latest news” links~~
- ~~missing social media icons on the bottom right (above footer)~~
- ~~subscribe field doesn’t read “email”~~
- ~~copyright footer reads “2020” not “2021”~~
- ~~“Terms of use” and “sitemap” have been switched around in footer~~

**Screenshots**
shorter breadcrumb trail & missing "latest news" section links:
<img width="1424" alt="Drupal_7_header" src="https://user-images.githubusercontent.com/31521411/109314799-d058e600-7817-11eb-86e4-a697d60541d5.png">
<img width="1396" alt="Drupal_9_header" src="https://user-images.githubusercontent.com/31521411/109314814-d51d9a00-7817-11eb-946b-a0aea6333054.png">

missing scroll arrow, social media links, advertisement, subscribe text reading "email", different copyright text
<img width="1417" alt="Drupal_7_footer" src="https://user-images.githubusercontent.com/31521411/109314830-d949b780-7817-11eb-9d82-db63b0b983e7.png">
<img width="1434" alt="Drupal_9_footer" src="https://user-images.githubusercontent.com/31521411/109314842-dc44a800-7817-11eb-874d-34c654346f16.png">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser: chrome

**Comment by jardix22** [comment]
@hatuhay The paragraph was updated but needs some styles.

**http://dev-icma-org.pantheonsite.io/coronavirus-crisis-response**
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/fd460435-c45c-43b1-a8ae-5c36e02f94ba)
