### ISSUE TITLE
Race, Equity, and Social Justice Page

### ISSUE THREAD

**Issue by mnewberg1** [isovera/icma#296]
**Describe the bug**
http://dev-icma-org.pantheonsite.io/race-equity-and-social-justice
compared to the D7 site, the D9 site has
- ~~“equity and inclusion” one article missing byline~~
- ~~“equity and inclusion” images are not clickable (but they are in D7)~~
- ~~highlighted content doesn't toggle~~
- ~~missing social media icons on the bottom right (above footer)~~
- ~~subscribe field doesn’t read “email”~~
- ~~copywriter footer reads “2020” not “2021”~~
- ~~“Terms of use” and “sitemap” have been switched around in footer~~

**Screenshots**
divider/ breadcrumb differences
<img width="1440" alt="D7_header" src="https://user-images.githubusercontent.com/31521411/109319121-86263380-781c-11eb-99c6-aa9bac32dec5.png">
<img width="1440" alt="D9_header" src="https://user-images.githubusercontent.com/31521411/109319138-89b9ba80-781c-11eb-824e-723707f24127.png">

highlight content doesn't toggle
<img width="1421" alt="D7_toggle" src="https://user-images.githubusercontent.com/31521411/109319258-ab1aa680-781c-11eb-8984-d5683f7bfed8.png">
<img width="1439" alt="D9_no_toggle" src="https://user-images.githubusercontent.com/31521411/109319279-afdf5a80-781c-11eb-832f-7127e69b5186.png">

equity & inclusion
<img width="1432" alt="D7_equity" src="https://user-images.githubusercontent.com/31521411/109319334-bec60d00-781c-11eb-98af-b92af00da6db.png">
<img width="1439" alt="D9_equity" src="https://user-images.githubusercontent.com/31521411/109319342-c08fd080-781c-11eb-8a41-fa56982dfb2d.png">

missing social/ advertisement/ field labeled "email"/ copyright
<img width="1439" alt="D7_footer" src="https://user-images.githubusercontent.com/31521411/109319435-ddc49f00-781c-11eb-92c4-fc2379035e34.png">
<img width="1440" alt="D9_footer" src="https://user-images.githubusercontent.com/31521411/109319440-df8e6280-781c-11eb-93d7-171e0d268cae.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome

**Comment by jardix22** [comment]
@hatuhay could you confirm the slideshow changes as I wrote in ticket #350, please.

**Comment by jardix22** [comment]
- **This node doesn't have a short description.**
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/c505772a-9912-4a2d-bb0f-1a169fd93799)

- **In that case, we should render the first 80 characters of the body field.**
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/bdca737f-d1bf-44e7-b731-0bf85677a9be)

- I didn't find any template or preprocess to put that logic. @hatuhay could you help me with that, please?

**Comment by hatuhay** [comment]
@jardix22 
Not styling but rendering.
Reassigning
