### ISSUE TITLE
Performance Management Pag

### ISSUE THREAD

**Issue by mnewberg1** [isovera/icma#305]
**Describe the bug**
Things of Note
http://dev-icma-org.pantheonsite.io/topics/performance-management
- ~~Body - D9 site missing “research and reports” content (this is an issue that will be solved with another migration)~~
- ~~Body - D9 site “learn more on performance…” section has two columns not three (this is an issue where the introduction of additional content will create additional columns)~~
- ~~Body - D9 site “view all on performance management” button leads to a page reading “The requested page could not be found.” Joseph is looking into this - it's a redirect issue and there are other examples in other tickets.~~
**Screenshots**
~~missing “research and reports” content; the “learn more on performance…” section has two columns not three~~
<img width="1440" alt="D7 body" src="https://user-images.githubusercontent.com/31521411/109360897-fac99400-7855-11eb-8ff3-21a3c369663a.png">
<img width="1440" alt="D9 body" src="https://user-images.githubusercontent.com/31521411/109360899-fac99400-7855-11eb-9536-a1fe9b460474.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome

**Comment by jardix22** [comment]
@hatuhay this news a `container` class or something like that to center the content.
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/9d445df5-7303-4b6a-a437-ab16519775d8)
