### ISSUE TITLE
Start Page

### ISSUE THREAD

**Issue by mnewberg1** [isovera/icma#306]
**Describe the bug**
http://dev-icma-org.pantheonsite.io/start
- ~~Body - D9 is missing images in sidebar & the “ETHICS PROMO” is not in D7~~
- ~~Body - D9 right sidebar menu looks different from D7 (items & what’s dropped down when you load the page)~~

**Screenshots**
right side bar - missing images & different ethics heading
<img width="524" alt="D7 right side" src="https://user-images.githubusercontent.com/31521411/109362180-7af0f900-7858-11eb-8e67-529347ef7840.png">
<img width="572" alt="D9 right side" src="https://user-images.githubusercontent.com/31521411/109362186-7c222600-7858-11eb-87bb-a3f45e7e8cd7.png">

right sidebar - menu content is different & D9 site loads with first menu option toggled down
<img width="380" alt="D7 side menu" src="https://user-images.githubusercontent.com/31521411/109362234-91975000-7858-11eb-99d3-1b134eff341e.png">
<img width="425" alt="D9 side menu" src="https://user-images.githubusercontent.com/31521411/109362235-91975000-7858-11eb-86da-501dc0e4889b.png">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser: chrome

**Comment by jardix22** [comment]
http://dev-icma-org.pantheonsite.io/start
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/095c7807-704b-45f5-909a-6bcc26f53b48)
