### ISSUE TITLE
Global Issue: Footer

### ISSUE THREAD

**Issue by mnewberg1** [isovera/icma#308]
**Describe the bug**
D9 site’s bottom advertisement block is empty
~~D9’s bottom subscribe field “email” text too dark to read easily~~

**Screenshots**
<img width="1440" alt="D7 footer" src="https://user-images.githubusercontent.com/31521411/109511995-a438a180-7a71-11eb-8724-37dfbd5c22bf.png">
<img width="1440" alt="D9 footer" src="https://user-images.githubusercontent.com/31521411/109512016-a864bf00-7a71-11eb-8a15-e7a51d374ce7.png">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Comment by eag603** [comment]
@jardix22 @hatuhay I noticed that this is crossed out:
D9’s bottom subscribe field “email” text too dark to read easily

But I still see it is too dark on the dev site.
