### ISSUE TITLE
Global Issue: Right Sidebar Media (Image)

### ISSUE THREAD

**Issue by mnewberg1** [isovera/icma#315]
**Describe the bug**
- ~~D9 site is missing their CTA image on the right side block. It reads "The referenced media source is missing and needs to be re-embedded." (as seen on "membership outside the US page in screenshots)~~
- ~~Unsure if related, but there's an empty double line under this cta block~~

**Screenshots**
<img width="1438" alt="D9 no media" src="https://user-images.githubusercontent.com/31521411/109659434-ac5a1500-7b35-11eb-8c12-83bf4112064c.png">
<img width="1440" alt="D7 media" src="https://user-images.githubusercontent.com/31521411/109659439-acf2ab80-7b35-11eb-8cf1-951d05356486.png">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Comment by jardix22** [comment]
@hatuhay It looks like the border block styles are unnecessary. 
http://dev-icma-org.pantheonsite.io/articles/member-news/remembrance
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/3791f6d2-145f-4dc9-adac-14ad596475de)

**Comment by hatuhay** [comment]
I was injecting the HR, now I see it is comming on the content itself
