### ISSUE TITLE
Members in Transition Page

### ISSUE THREAD

**Issue by mnewberg1** [isovera/icma#318]
**Describe the bug**
http://dev-icma-org.pantheonsite.io/members-transition
- D7 site has two right sidebar menus; D9 has one
- D9 page "Ethics" right sidebar content does not match D7

**Screenshots**
menus
<img width="804" alt="D7 menus" src="https://user-images.githubusercontent.com/31521411/109662042-9ef25a00-7b38-11eb-8f4b-f8ef0d16e7cd.png">
<img width="818" alt="D9 menu" src="https://user-images.githubusercontent.com/31521411/109662049-a0238700-7b38-11eb-8596-658823a22bbf.png">

ethics
<img width="553" alt="D9 ethics" src="https://user-images.githubusercontent.com/31521411/109662084-a9acef00-7b38-11eb-97a1-6a365c20f933.png">
<img width="474" alt="D7 ethics" src="https://user-images.githubusercontent.com/31521411/109662086-aa458580-7b38-11eb-9eca-ece4f9eb9aa6.png">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Comment by eag603** [comment]
@jardix22 assuming this matches the info architecture Andre provided us?
