### ISSUE TITLE
Member Exclusive: MPA Online Graduate Education Page

### ISSUE THREAD

**Issue by mnewberg1** [isovera/icma#320]
**Describe the bug**
http://dev-icma-org.pantheonsite.io/member-exclusive-mpa-online-graduate-education
- D9 site intro image is not sized correctly

**Screenshots**
<img width="1440" alt="D9 image" src="https://user-images.githubusercontent.com/31521411/109668447-32c72480-7b3f-11eb-90aa-b14883e53e86.png">
<img width="1440" alt="D7 image" src="https://user-images.githubusercontent.com/31521411/109668461-365aab80-7b3f-11eb-8938-d35a2690ecb0.png">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Comment by hatuhay** [comment]
@jardix22 , @eag603 
Inline styles missing on the image

**Comment by jardix22** [comment]
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/4ddd60a0-3279-4b4f-b36e-5f4738871c17)
