### ISSUE TITLE
"Ethics" block

### ISSUE THREAD

**Issue by mnewberg1** [isovera/icma#321]
**Describe the bug**
- ~~D9 header doesn't match & it's missing an image~~

**Screenshots**
<img width="493" alt="D7 ethics" src="https://user-images.githubusercontent.com/31521411/109669512-27c0c400-7b40-11eb-9f27-b6f8d49f7abc.png">
<img width="562" alt="D9 ethics" src="https://user-images.githubusercontent.com/31521411/109669518-28f1f100-7b40-11eb-9865-5d2945b350a0.png">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Comment by jardix22** [comment]
http://dev-icma-org.pantheonsite.io/start
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/674ce2a7-dbf3-4e7b-99a4-9cff72c76b6e)
