### ISSUE TITLE
The Senior Advisor Program Page

### ISSUE THREAD

**Issue by mnewberg1** [isovera/icma#322]
**Describe the bug**
http://dev-icma-org.pantheonsite.io/icma-senior-advisor-program
- D9 program review image is way too large **Inline style missing**
- ~~D9 related articles heading is cut off~~

**Screenshots**
D9 image too large
<img width="653" alt="D9 image" src="https://user-images.githubusercontent.com/31521411/109671252-e9c49f80-7b41-11eb-8399-47392ecda833.png">
<img width="769" alt="D7 image" src="https://user-images.githubusercontent.com/31521411/109671264-eb8e6300-7b41-11eb-8d52-224fe6bdf1d2.png">

"You may also be interested in" text cut off
<img width="733" alt="D7 related articles" src="https://user-images.githubusercontent.com/31521411/109671313-f6e18e80-7b41-11eb-9885-2823b1001b51.png">
<img width="753" alt="D9 related articles" src="https://user-images.githubusercontent.com/31521411/109671325-f8ab5200-7b41-11eb-8457-679d59688c95.png">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Comment by jardix22** [comment]
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/31b97da6-3e44-4c62-9e9e-4e5e1e3d98ba)
