### ISSUE TITLE
Scholarship Opportunities for ICMA Members Page

### ISSUE THREAD

**Issue by mnewberg1** [isovera/icma#323]
**Describe the bug**
http://dev-icma-org.pantheonsite.io/scholarship-opportunities-icma-members
- stretched image for Harvard Kennedy School
- headers are the same size as body text in D9

**Screenshots**
stretched image
<img width="637" alt="D9 image" src="https://user-images.githubusercontent.com/31521411/109674362-debf3e80-7b44-11eb-8816-77ef0c33b27d.png">
<img width="821" alt="D7 image" src="https://user-images.githubusercontent.com/31521411/109674367-dff06b80-7b44-11eb-8f80-b2da64fa1897.png">

Text sizing
<img width="666" alt="D7 text" src="https://user-images.githubusercontent.com/31521411/109674392-e41c8900-7b44-11eb-9729-29d290ebe8fe.png">
<img width="665" alt="D9 same size text" src="https://user-images.githubusercontent.com/31521411/109674396-e4b51f80-7b44-11eb-9b4d-ea7133d3efff.png">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Comment by hatuhay** [comment]
@jardix22 @eag603 
Inline styles missing on the image

**Comment by jardix22** [comment]
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/c2ac855a-97b8-4680-8ab9-617733905840)

**Comment by jardix22** [comment]
There are missing some margin styles when images are floating to the right or left. Please, @hatuhay help me with that. 

![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/183cdbeb-7ce8-4190-9160-ee46b7157eb0)
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/f2e66d49-91bb-482a-bae3-fec9172e8cca)

**Comment by hatuhay** [comment]
@jardix22 
Inline styles: assign Bootstrap standard class 'mr-3' to any element that requieres margin-right applied.
Other options will affect globally the site

**Comment by jardix22** [comment]
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/3588c6d5-5352-45f4-bf0f-6798b9df3d57)
