### ISSUE TITLE
top level nav items should expand on hover

### ISSUE THREAD

**Issue by eag603** [isovera/icma#325]
**Describe the bug**
When you mouse over top level menu items, i.e. Topics, Member Center, About ICMA, etc. the menu should expand as it does on D7.

**To Reproduce**
1. Go to http://dev-icma-org.pantheonsite.io
2. Mouse over any top level nav

**Expected behavior**
Menu should expand.

**Desktop (please complete the following information):**
- mac
- chrome

**Comment by hatuhay** [comment]
Modern sites does not open on hover.
Please confirm as this is current jstandard behaviour
