### ISSUE TITLE
Events and Conferences: Conferences page should have "conferences" filter selected

### ISSUE THREAD

**Issue by eag603** [isovera/icma#328]
~~When I visit: News & Events -->Conferences I should land on this page http://dev-icma-org.pantheonsite.io/events with "event type=conferences" checked.~~

See https://icma.org/events?field_event_type_tid%5B%5D=106

**Comment by jardix22** [comment]
@eag603 You can check the link again on the Main menu. Now the fixed link is http://dev-icma-org.pantheonsite.io/events?event_type%5B106%5D=106
