### ISSUE TITLE
Topics Right Sidebar: why does the styling look different on D7 than D9?

### ISSUE THREAD

**Issue by eag603** [isovera/icma#330]
The topics right sidebar on D7 looks like this:

<img width="1440" alt="Screen Shot 2021-03-02 at 8 41 10 PM" src="https://user-images.githubusercontent.com/60103535/109739586-d7755080-7b97-11eb-91cf-d460882e49ba.png">

On D9, it looks like this:

<img width="1343" alt="Screen Shot 2021-03-02 at 8 41 08 PM" src="https://user-images.githubusercontent.com/60103535/109739617-e65c0300-7b97-11eb-9491-ae458fef5e0f.png">

**Comment by hatuhay** [comment]
@eag603 
To match all the sidebar titles and bottom line
