### ISSUE TITLE
Might Also Like v. You may also be interested in

### ISSUE THREAD

**Issue by eag603** [isovera/icma#331]
On D7, the heading says "You may also be interested in"
On D9, it says "Might Also Like"

Should it say "You may also be interested in"?

<img width="982" alt="Screen Shot 2021-03-02 at 8 47 45 PM" src="https://user-images.githubusercontent.com/60103535/109740015-8580fa80-7b98-11eb-94b9-575062e0d1e1.png">
<img width="951" alt="Screen Shot 2021-03-02 at 8 47 37 PM" src="https://user-images.githubusercontent.com/60103535/109740020-87e35480-7b98-11eb-8037-a10afa9c2e78.png">

**Comment by jardix22** [comment]
**Fixed**
http://dev-icma-org.pantheonsite.io/articles/pm-magazine/pm-article-accessible-website
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/9a66f8d5-9aab-4712-b0d7-ec4abc3f6149)
