### ISSUE TITLE
Upcoming Events: should link to a page filtered by "Events Occurring-->Upcoming"

### ISSUE THREAD

**Issue by eag603** [isovera/icma#332]
Go to News & Events and click on "Upcoming Events"

You should land on a page with events filtered by "upcoming"

**Comment by jardix22** [comment]
**http://dev-icma-org.pantheonsite.io/events**
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/8a7883a7-6c15-4a84-ad2e-98603caf2a83)
