### ISSUE TITLE
Blog Page: missing ICMA Blog section at bottom of page

### ISSUE THREAD

**Issue by eag603** [isovera/icma#339]
**D7:**

![Screen Shot 2021-03-02 at 9.26.35 PM.png](https://images.zenhubusercontent.com/5e3b5a7454691a13cfdab601/eaa3445c-ba3b-4862-8d67-3aa672115a18)

**D9:**

![Screen Shot 2021-03-02 at 9.26.44 PM.png](https://images.zenhubusercontent.com/5e3b5a7454691a13cfdab601/d61cff15-2311-4ac8-8deb-eba2226069c4)

**Comment by jardix22** [comment]
The block is gone on D7.
