### ISSUE TITLE
Make a Contribution Page

### ISSUE THREAD

**Issue by mnewberg1** [isovera/icma#345]
**Describe the bug**
http://dev-icma-org.pantheonsite.io/make-contribution
- [ ] D9 site image displays alt text
- [ ] Also missing caption that is on d7 site: https://icma.org/make-contribution

**Screenshots**
<img width="278" alt="D7 to compare" src="https://user-images.githubusercontent.com/31521411/109897725-220ecf80-7c61-11eb-836d-d203fecc3a24.png">
<img width="256" alt="D9 alt text" src="https://user-images.githubusercontent.com/31521411/109897728-233ffc80-7c61-11eb-8e68-e2c8bb2bb7b3.png">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Comment by jardix22** [comment]
@hatuhay why are we rendering the **Alt Text for Lead Image** field as a caption image?

**D9**:
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/86cf93d8-a80e-4e50-b3e4-aba4e20dcd55)

**D7**:
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/ccf68fde-d152-4b6c-b874-02a778b013de)

**Comment by hatuhay** [comment]
@jardix22 
In some cases they use it in others they don't.
Now is consistence.
This is not styling by the way, so if you consider this should be taken out please do so.
