### ISSUE TITLE
Serve the Profession Page

### ISSUE THREAD

**Issue by mnewberg1** [isovera/icma#347]
**Describe the bug**
http://dev-icma-org.pantheonsite.io/serve-profession
- [ ] D9 site content layout different than D7

**Screenshots**
<img width="1079" alt="D7 content" src="https://user-images.githubusercontent.com/31521411/109898419-38695b00-7c62-11eb-9b19-81fc630f966f.png">
<img width="681" alt="D9 content" src="https://user-images.githubusercontent.com/31521411/109898423-3a331e80-7c62-11eb-89ba-35d5a2649705.png">

**Desktop (please complete the following information):**
 - OS: ios
 - Browser chrome

**Comment by eag603** [comment]
@mnewberg1 is this the D7 page you're comparing to? https://icma.org/serve-profession

**Comment by mnewberg1** [comment]
@eag603 yes, though it seems to be fixed now :)
