### ISSUE TITLE
Welcome, Teachers Page

### ISSUE THREAD

**Issue by mnewberg1** [isovera/icma#349]
**Describe the bug**
http://dev-icma-org.pantheonsite.io/welcome-teachers
- [x] D9 large empty space on bottom of page

**Screenshots**
<img width="1440" alt="D7 space" src="https://user-images.githubusercontent.com/31521411/109899127-5c796c00-7c63-11eb-8c28-e4375cde9629.png">
<img width="1255" alt="D9 space" src="https://user-images.githubusercontent.com/31521411/109899130-5d120280-7c63-11eb-9775-599ece7b2ce5.png">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Comment by jardix22** [comment]
The empty space is generated by the elements of the left sidebar as de in-page navigation. So, it's not an issue.
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/255c0a0b-33d6-43fb-b562-d03f6a6b0c1b)

**Comment by eag603** [comment]
it does seem like excessive white space but we can let it go for now and see if the client objects.
