### ISSUE TITLE
Ethics Page

### ISSUE THREAD

**Issue by mnewberg1** [isovera/icma#350]
**Describe the bug**
http://dev-icma-org.pantheonsite.io/ethics
- [ ] D9 page has no toggle slideshow
- [x] D9 page is missing an image in content

**Screenshots**
missing content
<img width="1098" alt="D7 content" src="https://user-images.githubusercontent.com/31521411/109899507-fa6d3680-7c63-11eb-9bfd-bd24914d5b45.png">
<img width="1175" alt="D9 content" src="https://user-images.githubusercontent.com/31521411/109899526-fe995400-7c63-11eb-94ef-26cd916dd73f.png">

slideshow
<img width="1065" alt="D9 slideshow" src="https://user-images.githubusercontent.com/31521411/109899540-0658f880-7c64-11eb-9e06-44385b18a32f.png">
<img width="1027" alt="D9 no slideshow" src="https://user-images.githubusercontent.com/31521411/109899550-0953e900-7c64-11eb-88bb-a8123702103b.png">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Comment by jardix22** [comment]
@hatuhay Why the position of the slideshow's sidebar is on the left side?  Also, it's missing the slideshow left & right toggle buttons to change the slide. If those changes were intentionally got rid of as improvement, please add the "Inform client" tag. Also, add that tag on tickets where the same issue was reported. 

![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/ca63f177-4cb1-45a8-a14c-04e28fa1b73b)

**Comment by hatuhay** [comment]
@jardix22 
Usability
Answered on a different ticket
