### ISSUE TITLE
Enforcing the ICMA Code of Ethics Page

### ISSUE THREAD

**Issue by mnewberg1** [isovera/icma#352]
**Describe the bug**
http://dev-icma-org.pantheonsite.io/enforcing-icma-code-ethics
- [ ] D9 framework is bullets, D7 is numbers

**Screenshots**
<img width="702" alt="D7 numbers" src="https://user-images.githubusercontent.com/31521411/109900227-00afe280-7c65-11eb-907b-0a316b9446e2.png">
<img width="639" alt="D9 bullets" src="https://user-images.githubusercontent.com/31521411/109900230-01487900-7c65-11eb-8467-5d7e73a1b1f6.png">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Comment by jardix22** [comment]
@hatuhay Why are you overriding the **Order List** default styles to use bullets instead of numbers? Is that right?
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/194c6803-b055-4b76-8416-6b6cc312f632)

**Comment by hatuhay** [comment]
@jardix22 
Inherit styles, garbage now
