### ISSUE TITLE
Ethics Training Page

### ISSUE THREAD

**Issue by mnewberg1** [isovera/icma#353]
**Describe the bug**
http://dev-icma-org.pantheonsite.io/ethics-training
- [x] D9 image has alt text, D7 does not
- [x] D9 articles missing images

**Screenshots**
alt text
<img width="285" alt="D7 no alt text" src="https://user-images.githubusercontent.com/31521411/109900559-921f5480-7c65-11eb-9f41-6c0bfcba81ad.png">
<img width="243" alt="D9 alt text" src="https://user-images.githubusercontent.com/31521411/109900563-92b7eb00-7c65-11eb-9f9b-9f43dd497186.png">

D9 missing images
<img width="631" alt="D9 image missing" src="https://user-images.githubusercontent.com/31521411/109900571-977c9f00-7c65-11eb-8c0d-6fb2a86bfd12.png">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Comment by jardix22** [comment]
**D9 image has alt text, D7 does not**

**D9 articles missing images**
Not all the articles have a lead image. So, in those cases, the article is rendered like this:
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/464c04b4-9ad9-4d94-8413-5d8ba579508d)

**Comment by eag603** [comment]
@jardix22 why isn't the alt text the same on d9 as it is in d7? https://icma.org/ethics-training

(VIA ICMA v. men and woman in meeting room
ICMA)
