### ISSUE TITLE
Device testing: ICMA Strategic Partners Page

### ISSUE THREAD

**Issue by mnewberg1** [isovera/icma#354]
**Describe the bug**
http://dev-icma-org.pantheonsite.io/strategic-partners
When viewed on mobile or tablet, images become stretched

**Screenshots**
<img width="339" alt="mobile stretch" src="https://user-images.githubusercontent.com/31521411/110022931-87fb6580-7cfa-11eb-88ee-59101261923f.png">
<img width="474" alt="ipad stretched graphics" src="https://user-images.githubusercontent.com/31521411/110022934-8893fc00-7cfa-11eb-80d9-6d4cf7acbe64.png">

**Smartphone (please complete the following information):**
 - Device: pixel 2 (also iphone x)
 - Browser chrome

 - Device: ipad pro

**Comment by eag603** [comment]
It' slike this on  their prod site too.
