### ISSUE TITLE
Device Testing: Mobile menu

### ISSUE THREAD

**Issue by mnewberg1** [isovera/icma#360]
**Describe the bug**
- [ ]  Menu bar scrolls with page on D7 but not on D9 (used screenshot from homepage even though it happens on all pages, scrolled down to Coronavirus section) on mobile

**Screenshots**
<img width="293" alt="d9 home menu" src="https://user-images.githubusercontent.com/31521411/110518925-bef6c000-80da-11eb-8c49-6ff42972697a.png">

<img width="293" alt="d7 home menu" src="https://user-images.githubusercontent.com/31521411/110518884-b1413a80-80da-11eb-940d-cf46ed0b00e8.png">

**Smartphone (please complete the following information):**
 - Device: iphone
 - Browser chrome

**Comment by eag603** [comment]
@mnewberg1 can you retest?

**Comment by mnewberg1** [comment]
Fixed! Thanks!
