### ISSUE TITLE
Device Testing: The Senior Advisor Program page

### ISSUE THREAD

**Issue by mnewberg1** [isovera/icma#361]
**Describe the bug**
http://dev-icma-org.pantheonsite.io/icma-senior-advisor-program
- [ ] Under “you may also be interested”, the D9 articles render funny using mobile

**Screenshots**
<img width="295" alt="D9 you may also be" src="https://user-images.githubusercontent.com/31521411/110519046-e0f04280-80da-11eb-946f-3371095554e6.png">
<img width="295" alt="d7 you may also be" src="https://user-images.githubusercontent.com/31521411/110519073-e6e62380-80da-11eb-9e8d-29e6e135cfc1.png">

**Smartphone (please complete the following information):**
 - Device: iphone
 - Browser chrome

**Comment by eag603** [comment]
@mnewberg1 can you retest?

**Comment by mnewberg1** [comment]
articles fixed; thank you!
