### ISSUE TITLE
Device Testing: Member Center Page

### ISSUE THREAD

**Issue by mnewberg1** [isovera/icma#362]
**Describe the bug**
http://dev-icma-org.pantheonsite.io/member-center
- [ ] Member Center page - ‘Social Justice Resources‘ section has a strange popup box on the D9 site on mobile

**Screenshots**
<img width="294" alt="D7 social justice resources" src="https://user-images.githubusercontent.com/31521411/110519342-30367300-80db-11eb-93c8-f95583ee86ec.png">
<img width="293" alt="D9 social justice resources" src="https://user-images.githubusercontent.com/31521411/110519584-80153a00-80db-11eb-9a84-7a41a00312cc.png">

**Smartphone (please complete the following information):**
 - Device: iphone
 - Browser chrome

**Comment by eag603** [comment]
@mnewberg1 can you retest?

**Comment by mnewberg1** [comment]
popup has been removed; thanks!
