### ISSUE TITLE
Missing Job listing filters

### ISSUE THREAD

**Issue by jardix22** [isovera/icma#369]
- [x] Geo filter
- [x] Range salary

**Comment by eag603** [comment]
@jardix22 is this  the filters you're working on? http://dev-icma-org.pantheonsite.io/job-listings

**Comment by jardix22** [comment]
Yes, They are on the left sidebar @eag603 
![image.png](https://images.zenhubusercontent.com/5fb82b8dd06a063def843f8a/ba5c9aa1-3ba6-43ab-a491-97b9ae1c1829)
