### ISSUE TITLE
What We Do page

### ISSUE THREAD

**Issue by mnewberg1** [isovera/icma#373]
**Describe the bug**
http://dev-icma-org.pantheonsite.io/what-we-do
- [x] red "download" cta is off centered from media in D9

**Screenshots**
<img width="930" alt="Screen Shot 2021-03-11 at 12 07 20 PM" src="https://user-images.githubusercontent.com/31521411/110826056-b16c4200-8262-11eb-958a-645e5a2fbdbc.png">
<img width="1030" alt="Screen Shot 2021-03-11 at 12 07 12 PM" src="https://user-images.githubusercontent.com/31521411/110826060-b3360580-8262-11eb-838e-e33bfbafb654.png">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Comment by hatuhay** [comment]
@jardix22 
Inline styles.
'text-center' Bootstrap class could do the job
