### ISSUE TITLE
Connect PAGE

### ISSUE THREAD

**Issue by mnewberg1** [isovera/icma#378]
**Describe the bug**
http://dev-icma-org.pantheonsite.io/connect
- [ ] Social media icons for Linkedin, Instagram, and youtube (but not the text) link to 404 pages.

**Screenshots**
<img width="907" alt="icons to 404" src="https://user-images.githubusercontent.com/31521411/110959959-3ebf9d00-831c-11eb-8b79-f7b356391d40.png">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Comment by jardix22** [comment]
It's not a migration issue If you go to the https://icma.org/connect page and click on those images there link to 404 pages, too.
So, It's a client content issue.
