### ISSUE TITLE
Requests For Proposals page

### ISSUE THREAD

**Issue by mnewberg1** [isovera/icma#380]
**Describe the bug**
http://dev-icma-org.pantheonsite.io/requests-for-proposals
- [ ] RFP Download buttons in "ICMAHO/ICMA Code of Ethics Bias Assessment" section aren't evenly spaced on D9

**Screenshots**
<img width="1440" alt="d7 rfp" src="https://user-images.githubusercontent.com/31521411/110961562-ee493f00-831d-11eb-95e3-1195aaedb755.png">
<img width="1440" alt="d9 rfp" src="https://user-images.githubusercontent.com/31521411/110961571-f0130280-831d-11eb-9366-c67eae86e666.png">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Comment by hatuhay** [comment]
@jardix22 
Inline styles, 'mb-3' Bootstrap class could help
