### ISSUE TITLE
ICMA Coaching Program Webinars page

### ISSUE THREAD

**Issue by mnewberg1** [isovera/icma#388]
**Describe the bug**
http://dev-icma-org.pantheonsite.io/icma-coaching-program-webinars
- [x] D7 CTA is center aligned; D9 is left aligned

**Screenshots**
![d9 left align.png](https://images.zenhubusercontent.com/5fd28e9a5a6b99683d152753/80aa18f8-4f1b-4c81-b963-bd734bc9d5bc)
![d7 centered.png](https://images.zenhubusercontent.com/5fd28e9a5a6b99683d152753/35644640-2bda-42a7-b299-85ac804d2e0e)

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Comment by hatuhay** [comment]
@jardix22 
Inline styles: replace 'rtecenter' class with standard Bootstrap class 'text-center'
