### ISSUE TITLE
ICMA Coaching Program Advisory Committee page

### ISSUE THREAD

**Issue by mnewberg1** [isovera/icma#392]
**Describe the bug**
http://dev-icma-org.pantheonsite.io/coaching-program-partnerssponsors
- [ ] I'm not sure if it's relevant or not, but the headings on D7 differ from D9 (they're bolded & not italicized)

**Screenshots**
<img width="654" alt="D9 headings" src="https://user-images.githubusercontent.com/31521411/111222231-f02b3080-85b1-11eb-9834-6988ca95cf90.png">
<img width="756" alt="D7 headings" src="https://user-images.githubusercontent.com/31521411/111222236-f15c5d80-85b1-11eb-8c29-0fd6874c15a3.png">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Comment by eag603** [comment]
This is an artifact of Alberto creating more consistency.
